face_rating/account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = "account"
urlpatterns = [
    path("signup/",views.signup,name="signup"),
    path("signin/",views.signin,name="signin"),
    path("signout/",views.signout,name="signout"),
    path("face-id/",views.face_id,name="face_id"),
    path("face_login/",views.face_id_to_login,name="face_login"),
]

face_rating/face_rating/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('recog-app/', include('face_recognition_app.urls')),
    path('', include('face_rating_app.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

face_rating/face_rating_app/urls.py
from django.urls import path
from . import views
app_name = "face_rating_app"
urlpatterns = [
    path('', views.face_rating, name='face_rating'),
    # path('', views.home, name='home'),
    path('upload/', views.upload_view, name='upload'),

]

face_rating/face_recognition_app/urls.py
from django.urls import path
from . import views
app_name = "face_recognition_app"
urlpatterns = [
    path('face_login/', views.face_recognition_view, name='face_recognition_app'),
    path('video_feed/', views.video_feed, name='video_feed'),
    path('stop_webcam/', views.stop_webcam, name='stop_webcam'),

]

face_rating/face_rating_app/models.py
from django.db import models
from account.models import AccountModel

class RatingSessionsModel(models.Model):
    account = models.ForeignKey(AccountModel, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.id} - {self.created_at}"

class RatingModel(models.Model):
    session = models.ForeignKey(RatingSessionsModel, on_delete=models.CASCADE)
    eye_point = models.FloatField()
    nose_point = models.FloatField()
    jawline_point = models.FloatField()
    mouth_point = models.FloatField()
    mean_point = models.FloatField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Rating for {self.session}"

face_rating/face_rating_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from imutils import face_utils
import dlib
import cv2
from .score_model import ScoreModel
from django.conf import settings
import os
import base64
from io import BytesIO
from PIL import Image
import numpy as np
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from face_recognition_app.views import close_camera
from .models import RatingModel, RatingSessionsModel
from account.models import AccountModel

def face_rating(request):
    close_camera()
    if request.method == "POST":
        try:
            base64_string = request.POST.get("imageData")
            header, base64_data = base64_string.split(';base64,')
            image_data = base64.b64decode(base64_data)
            image = np.array(Image.open(BytesIO(image_data)))
            result,edited_image_path = scoring_face(image)
            with open(edited_image_path, "rb") as img_file:
                img_base64 = base64.b64encode(img_file.read()).decode('utf-8')
            try:
                account = AccountModel.objects.get(username = request.user.username)
                session_model = RatingSessionsModel.objects.create(
                    account = account
                )

                rating_model = RatingModel.objects.create(
                        session = session_model,
                        eye_point = result["point"]["Eye"],
                        nose_point = result["point"]["Nose"],
                        jawline_point = result["point"]["Jawline"],
                        mouth_point = result["point"]["Mouth"],
                        mean_point = result["point"]["Mean"]
                )
                if rating_model:
                    print("Them vao db thanh cong")
            except Exception:
                print(Exception)
            return JsonResponse({
                'result': result,
                'edited_image': img_base64
            })
        except:
            print("error")
    return render(request,"face_rating_app/face_rating.html")

def scoring_face(image):
    close_camera()
    p = os.path.join(settings.MEDIA_ROOT, "algorithm_files", "shape_predictor_68_face_landmarks.dat")
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(p)

    # Load the image and convert it to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detect faces in the grayscale image
    rects = detector(gray, 0)

    for (i, rect) in enumerate(rects):
        shape = predictor(gray, rect)
        shape = face_utils.shape_to_np(shape)

        left_eye = shape[36:42]
        right_eye = shape[42:48]
        nose_points = shape[27:35]
        mouth_points = shape[48:67]
        jawline_points = shape[0:17]

        # Draw the contours and landmarks
        cv2.polylines(image, [left_eye], isClosed=True, color=(255, 0, 0), thickness=1)
        cv2.polylines(image, [right_eye], isClosed=True, color=(255, 0, 0), thickness=1)
        cv2.polylines(image, [nose_points], isClosed=True, color=(255, 255, 0), thickness=1)
        cv2.polylines(image, [mouth_points], isClosed=True, color=(255, 255, 255), thickness=1)
        cv2.polylines(image, [jawline_points], isClosed=False, color=(0, 255, 255), thickness=1)

        for (x, y) in left_eye:
            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)
        for (x, y) in right_eye:
            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)
        for (x, y) in nose_points:
            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)
        for (x, y) in mouth_points:
            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)
        for (x, y) in jawline_points:
            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)

        model = ScoreModel(shape)
        result = model.final_result()
        
    
        # Save the edited image
        output_path = os.path.join(settings.MEDIA_ROOT,"images", "edited_images", "edited_image.jpg")
        cv2.imwrite(output_path, image)

        return result, output_path

@csrf_exempt
def upload_view(request):
    close_camera()
    
    if request.method == 'POST' and request.FILES.get('image'):
        image_file = request.FILES['image']
        
        image_pil = Image.open(image_file)
        image_np = np.array(image_pil)

        if image_np.shape[2] == 4:  
            image_np = cv2.cvtColor(image_np, cv2.COLOR_RGBA2RGB)

        result, edited_image_path = scoring_face(image_np)
        # result = str(result)
        try:
            account = AccountModel.objects.get(username = request.user.username)
            print(account.email)
            session_model = RatingSessionsModel.objects.create(
                account = account
            )
            print(session_model)
            print("Point",type(result))
            rating_model = RatingModel.objects.create(
                session = session_model,
                eye_point = result["point"]["Eye"],
                nose_point = result["point"]["Nose"],
                jawline_point = result["point"]["Jawline"],
                mouth_point = result["point"]["Mouth"],
                mean_point = result["point"]["Mean"]
            )
            if rating_model:
                print("Them vao db thanh cong")
        except Exception:
                print(Exception)
        # Convert edited image to base64 to include in response
        with open(edited_image_path, "rb") as img_file:
            img_base64 = base64.b64encode(img_file.read()).decode('utf-8')
  
        return JsonResponse({
            'result': result,
            'edited_image': img_base64
        })
    return JsonResponse({'message': 'Invalid request'}, status=400)

face_rating/face_rating_app/templates/face_rating_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intellicon - AI and Machine Learning</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    {% block css %}
        
    {% endblock css %}
</head>
<body>
    <header>
        <div class="container">
            <div class="logo">
            </div>
            <nav>
                <ul>
                   
                    <li><a href="{% url 'face_recognition_app:face_recognition_app' %}">Face recognition</a></li>
                    <li><a href="{% url 'face_rating_app:face_rating' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="">{{request.user.username}}</a></li>

                    <li><a href="{% url 'account:signout'  %}">Signout</a></li>
                    {% else %}
                    <li><a href="{% url 'account:signin'  %}">Signin</a></li>
                    <br>
                    <br>
                    <li><a href="{% url 'account:signup'  %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="sign-in">
              
              
            </div>
        </div>
    </header>
    <div id = "content_container">

    {% block content %}
        
    {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        
    
    {% block js %}
        
    {% endblock js %}
</body>
</html>

face_rating/face_rating_app/templates/face_rating_app/face_rating.html
{% extends "face_rating_app/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/face_id.css' %}">
<link rel="stylesheet" href="{% static 'css/bground.css' %}">
{% endblock css %}
{% block content %}
<div class="get-picture-group">
    <div id="result-container">
        <div class="rating_section" id="rating_section">
            <div class="rating_item">
                <h2>Hàm: <h2 id="point_rating_jawline"></h2></h2>
            </div>
            <div class="rating_item">
                <h2>Mũi: <h2 id="point_rating_nose"></h2></h2>
            </div>
            <div class="rating_item">
                <h2>Mắt: <h2 id="point_rating_eye"></h2></h2>
            </div>
            <div class="rating_item">
                <h2>Môi: <h2 id="point_rating_lip"></h2></h2>
            </div>
            <div class="rating_item">
                <h2>Tổng thể khuôn mặt: </h2>
                <h5 id="result" style="color: black;"></h5>
            </div>
        </div>
        <img id="editedImage" src="" alt="Edited Image"  height="15%" width="20%" style="display: none;"/>

    </div>
        
        <div class="overlay">
            <div id= "intro">
            <h1>Am I Beautiful or Ugly?</h1>
            <p>Am I pretty ? Am I ugly ? <br>
            Why am I ugly ? or not pretty enough ?<br>
            Online test for face beauty analysis.<br>
            Analyze your face in 1 minutes.<br>
            Rate my face 1-10. How beautiful am I?<br>
            Are you pretty? Ask us with confidentiality.<br>
            Upload photo or use webcam.</p>
            <div class="test-options">
              <a href="{% url 'face_recognition_app:face_recognition_app' %}" class="test-btn">Face test</a>
              <button class="test-btn" id="face_rating_btn">Face Rating</button>  
            </div>
        </div>
            <hr>
            <div class="action-buttons" style="display: none;">
                    <button id="take_photo"></button>
                    <button id="select_photo"></button>
                    <input type="file" id="select_picture" hidden>
            </div>

        </div>
    
    <div id="video-container2" style="display: none;">
        <div id="video_rating" style="position: absolute;;top: 50%;left: 50%;transform: translate(-50%, -50%)">
            <video src="" id="video-webcam" height="480" width="640" autoplay style="border: 5px dashed rgba(0, 106, 255, 0.726); transform: scaleX(-1);"></video>
        </div>
        <canvas width="640" height="480"></canvas>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" id="btn">Enter</button>
                <input type="text" name="imageData" id="imageData" hidden>
            </form>
        </div>
    </div>
   
</div>
{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/face_rating.js' %}"></script>

{% endblock js %}
{% endblock content %}

face_rating/face_rating_app/templates/face_rating_app/home.html
{% extends "face_rating_app/base.html" %}
{% load static %}

{% block css %}
{% endblock css %}

{% block content %}
<main>
    <section class="hero">
        <div class="container">
            <div class="hero-text">
                <h2>FACE RECOGNITION <span class="highlight">&</span> FACIAL SCORING</h2>
                <h1>Am I Beautiful or Ugly?</h1>
                <p>Am I pretty? Am I ugly?<br>
                    Why am I ugly? or not pretty enough?<br>
                    Online test for face beauty analysis.<br>
                    Analyze your face in 3 minutes.<br>
                    Rate my face 1-100. How beautiful am I?<br>
                    Are you pretty? Ask us with confidentiality.<br>
                    Upload photo or use webcam.</p>

                <div class="hero-buttons">
                    <a href="#" class="btn-get-started">Face Test</a>
                </div>
            </div>
            <div class="hero-images">
                <img src="{% static 'images/banner1.png' %}" alt="AI Robot">
                <img src="{% static 'images/ai-element.png' %}" alt="Brain" class="ai-element">
            </div>
        </div>
    </section>
</main>
{% endblock content %}

{% block js %}
{% endblock js %}

face_rating/face_rating_app/templates/face_rating_app/index.html
{% extends "face_rating_app/base.html" %}
{% load static %}

{% block css %}
{% endblock css %}

{% block content %}
<main>
    <section class="hero">
        <div class="container">
            <div class="hero-text">
                <h2>FACE RECOGNITION <span class="highlight">&</span> FACIAL SCORING</h2>
                <h1>Am I Beautiful or Ugly?</h1>
                <p>Am I pretty? Am I ugly?<br>
                    Why am I ugly? or not pretty enough?<br>
                    Online test for face beauty analysis.<br>
                    Analyze your face in 3 minutes.<br>
                    Rate my face 1-100. How beautiful am I?<br>
                    Are you pretty? Ask us with confidentiality.<br>
                    Upload photo or use webcam.</p>

                <div class="hero-buttons">
                    <a href="#" class="btn-get-started">Face Test</a>
                </div>
            </div>
            <div class="hero-images">
                <img src="{% static 'images/banner1.png' %}" alt="AI Robot">
                <img src="{% static 'images/ai-element.png' %}" alt="Brain" class="ai-element">
            </div>
        </div>
    </section>
</main>
{% endblock content %}

{% block js %}
{% endblock js %}